### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pickles/allAssemblies.p'

### ISSUE THREAD

**Issue by Rmmendoza** [skDooley/TRACR_RNA#1]
Dear Dr. Dooley, 

Good day. I am trying to run your scripts to find TracrRNA from my bacterial genomes. I have just started running the scripts, but I found an error that says: FileNotFoundError: [Errno 2] No such file or directory: 'pickles/allAssemblies.p'. 

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-be751ed21d94> in <module>
     20 theDate = date.today()
     21 print("Ready to dump")
---> 22 dump(allAssemblies,open("pickles/allAssemblies.p","wb"))
     23 print("Number of assemblies on %s: %i" % (theDate, len(allAssemblies)))

FileNotFoundError: [Errno 2] No such file or directory: 'pickles/allAssemblies.p'

I checked the pickles directory and true enough the only file there is the CasTree.p. May I know where can I get the allAssemblies.p? And if there's any, kindly let me know if I'm doing something wrong hence the error. 

Thank you very much for your help.

**Comment by skDooley** [comment]
Hi Remilyn,

That line is trying to write that file ('wb'). It looks like wherever your
notebook is running from doesn't have direct access to the pickles
directory. Use
import os
os.chdir(<directory with the pickles folder in it>)

or

%%bash
mkdir pickles

If you have any other problems or questions, feel free to email me directly
***@***.***
